# Generated by Django 2.2 on 2020-10-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure', models.CharField(max_length=350)),
                ('destination', models.CharField(max_length=350)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ride', to=settings.AUTH_USER_MODEL)),
                ('joined_by', models.ManyToManyField(related_name='joined_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
